import { AllowedTags, AllowedCSS } from "./../types/phantomExorciser";

/*
phantomExorciser tag, attrribute, and CSS allowlists
*/

function unconstrained(attribute: string | null) {
  return attribute;
}

export const allowedAttributes = {
  abbr: unconstrained,
  accept: unconstrained,
  "accept-charset": unconstrained,
  accesskey: unconstrained,
  action: unconstrained,
  align: unconstrained,
  alt: unconstrained,
  autocomplete: unconstrained,
  autosave: unconstrained,
  axis: unconstrained,
  bgcolor: unconstrained,
  border: unconstrained,
  cellpadding: unconstrained,
  cellspacing: unconstrained,
  challenge: unconstrained,
  char: unconstrained,
  charoff: unconstrained,
  charset: unconstrained,
  checked: unconstrained,
  cite: unconstrained,
  class: unconstrained,
  clear: unconstrained,
  color: unconstrained,
  cols: unconstrained,
  colspan: unconstrained,
  compact: unconstrained,
  contenteditable: unconstrained,
  coords: unconstrained,
  datetime: unconstrained,
  dir: unconstrained,
  disabled: unconstrained,
  draggable: unconstrained,
  dropzone: unconstrained,
  enctype: unconstrained,
  for: unconstrained,
  frame: unconstrained,
  headers: unconstrained,
  height: unconstrained,
  high: unconstrained,
  href: unconstrained,
  hreflang: unconstrained,
  hspace: unconstrained,
  ismap: unconstrained,
  id: unconstrained,
  keytype: unconstrained,
  label: unconstrained,
  lang: unconstrained,
  list: unconstrained,
  longdesc: unconstrained,
  low: unconstrained,
  max: unconstrained,
  maxlength: unconstrained,
  media: unconstrained,
  method: unconstrained,
  min: unconstrained,
  multiple: unconstrained,
  name: unconstrained,
  nohref: unconstrained,
  noshade: unconstrained,
  novalidate: unconstrained,
  nowrap: unconstrained,
  open: unconstrained,
  optimum: unconstrained,
  pattern: unconstrained,
  placeholder: unconstrained,
  prompt: unconstrained,
  pubdate: unconstrained,
  radiogroup: unconstrained,
  readonly: unconstrained,
  rel: unconstrained,
  required: unconstrained,
  rev: unconstrained,
  reversed: unconstrained,
  rows: unconstrained,
  rowspan: unconstrained,
  rules: unconstrained,
  scope: unconstrained,
  selected: unconstrained,
  shape: unconstrained,
  size: unconstrained,
  span: unconstrained,
  spellcheck: unconstrained,
  src: unconstrained,
  start: unconstrained,
  step: unconstrained,
  style: unconstrained,
  summary: unconstrained,
  tabindex: unconstrained,
  target: unconstrained,
  title: unconstrained,
  type: unconstrained,
  usemap: unconstrained,
  valign: unconstrained,
  value: unconstrained,
  vspace: unconstrained,
  width: unconstrained,
  wrap: unconstrained,
};

export const allowedTags: AllowedTags = {
  a: allowedAttributes,
  abbr: allowedAttributes,
  acronym: allowedAttributes,
  address: allowedAttributes,
  area: allowedAttributes,
  article: allowedAttributes,
  aside: allowedAttributes,
  b: allowedAttributes,
  bdi: allowedAttributes,
  big: allowedAttributes,
  blockquote: allowedAttributes,
  br: allowedAttributes,
  button: allowedAttributes,
  caption: allowedAttributes,
  center: allowedAttributes,
  cite: allowedAttributes,
  code: allowedAttributes,
  col: allowedAttributes,
  colgroup: allowedAttributes,
  data: allowedAttributes,
  datalist: allowedAttributes,
  dd: allowedAttributes,
  del: allowedAttributes,
  details: allowedAttributes,
  dfn: allowedAttributes,
  dir: allowedAttributes,
  div: allowedAttributes,
  dl: allowedAttributes,
  dt: allowedAttributes,
  em: allowedAttributes,
  fieldset: allowedAttributes,
  figcaption: allowedAttributes,
  figure: allowedAttributes,
  font: allowedAttributes,
  footer: allowedAttributes,
  form: allowedAttributes,
  h1: allowedAttributes,
  h2: allowedAttributes,
  h3: allowedAttributes,
  h4: allowedAttributes,
  h5: allowedAttributes,
  h6: allowedAttributes,
  header: allowedAttributes,
  hr: allowedAttributes,
  i: allowedAttributes,
  img: allowedAttributes,
  input: allowedAttributes,
  ins: allowedAttributes,
  kbd: allowedAttributes,
  keygen: allowedAttributes,
  label: allowedAttributes,
  legend: allowedAttributes,
  li: allowedAttributes,
  main: allowedAttributes,
  map: allowedAttributes,
  mark: allowedAttributes,
  menu: allowedAttributes,
  menuitem: allowedAttributes,
  meter: allowedAttributes,
  nav: allowedAttributes,
  ol: allowedAttributes,
  optgroup: allowedAttributes,
  option: allowedAttributes,
  output: allowedAttributes,
  p: allowedAttributes,
  pre: allowedAttributes,
  progress: allowedAttributes,
  q: allowedAttributes,
  rp: allowedAttributes,
  rt: allowedAttributes,
  ruby: allowedAttributes,
  s: allowedAttributes,
  samp: allowedAttributes,
  section: allowedAttributes,
  select: allowedAttributes,
  small: allowedAttributes,
  span: allowedAttributes,
  strike: allowedAttributes,
  strong: allowedAttributes,
  sub: allowedAttributes,
  summary: allowedAttributes,
  sup: allowedAttributes,
  table: allowedAttributes,
  tbody: allowedAttributes,
  td: allowedAttributes,
  textarea: allowedAttributes,
  tfoot: allowedAttributes,
  th: allowedAttributes,
  thead: allowedAttributes,
  time: allowedAttributes,
  tr: allowedAttributes,
  tt: allowedAttributes,
  u: allowedAttributes,
  ul: allowedAttributes,
  var: allowedAttributes,
  wbr: allowedAttributes,
};

export const allowedCSS: AllowedCSS = [
  "background",
  "background-attachment",
  "background-clip",
  "background-color",
  "background-image",
  "background-origin",
  "background-position",
  "background-repeat",
  "background-size",
  "border",
  "border-bottom",
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-collapse",
  "border-color",
  "border-image",
  "border-image-outset",
  "border-image-repeat",
  "border-image-slice",
  "border-image-source",
  "border-image-width",
  "border-left",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-spacing",
  "border-style",
  "border-top",
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width",
  "bottom",
  "caption-side",
  "clear",
  "clip",
  "color",
  "content",
  "counter-increment",
  "counter-reset",
  "cursor",
  "direction",
  "display",
  "empty-cells",
  "float",
  "font",
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-language-override",
  "font-size",
  "font-size-adjust",
  "font-stretch",
  "font-style",
  "font-synthesis",
  "font-variant",
  "font-variant-alternates",
  "font-variant-caps",
  "font-variant-east-asian",
  "font-variant-ligatures",
  "font-variant-numeric",
  "font-variant-position",
  "font-weight",
  "height",
  "left",
  "letter-spacing",
  "line-height",
  "list-style",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "margin",
  "margin-bottom",
  "margin-left",
  "margin-right",
  "margin-top",
  "max-height",
  "max-width",
  "min-height",
  "min-width",
  "opacity",
  "orphans",
  "outline",
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
  "overflow",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "padding",
  "padding-bottom",
  "padding-left",
  "padding-right",
  "padding-top",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "quotes",
  "right",
  "table-layout",
  "text-align",
  "text-decoration",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-skip",
  "text-decoration-style",
  "text-indent",
  "text-transform",
  "top",
  "unicode-bidi",
  "vertical-align",
  "visibility",
  "white-space",
  "widows",
  "width",
  "word-spacing",
  "z-index",
];
